// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfATxRTSi8uuvRBAKFQFETN0HsgiXplmk',
    appId: '1:566072029937:web:1add29da3ad9ad82946f50',
    messagingSenderId: '566072029937',
    projectId: 'flutter-chat-app-f9424',
    authDomain: 'flutter-chat-app-f9424.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f9424.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLyJ16pnuO1pg4LL6YfKsLoOVYZip9qw',
    appId: '1:566072029937:android:9c954cbb04ae13a0946f50',
    messagingSenderId: '566072029937',
    projectId: 'flutter-chat-app-f9424',
    storageBucket: 'flutter-chat-app-f9424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAX20HtWJMSsdxTj1vlwCSPV7BhEHcxTY',
    appId: '1:566072029937:ios:1cb268907cbdbb0f946f50',
    messagingSenderId: '566072029937',
    projectId: 'flutter-chat-app-f9424',
    storageBucket: 'flutter-chat-app-f9424.appspot.com',
    iosClientId: '566072029937-hjre66904bg4a881c1lasgjk8th7snv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAX20HtWJMSsdxTj1vlwCSPV7BhEHcxTY',
    appId: '1:566072029937:ios:1cb268907cbdbb0f946f50',
    messagingSenderId: '566072029937',
    projectId: 'flutter-chat-app-f9424',
    storageBucket: 'flutter-chat-app-f9424.appspot.com',
    iosClientId: '566072029937-hjre66904bg4a881c1lasgjk8th7snv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
